name: easy_maps_plus
description: Draw routes and calculate distances easily with Google Maps in Flutter.
version: 0.1.1
homepage: https://github.com/D3R50N/easy_maps_plus

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.4.0
  http: ^1.1.0

repository: https://github.com/D3R50N/easy_maps_plus

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
